### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'header' of undefined

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-dashboard#231]
Just hit a fatal uncaught exception from `ui.js`:
```
    16 May 16:10:40 - [info] Stopped flows
    16 May 16:10:40 - [info] Starting flows
    16 May 16:10:40 - [info] Started flows
    16 May 16:10:40 - [red] Uncaught Exception:
    16 May 16:10:40 - TypeError: Cannot read property 'header' of undefined
        at Socket.<anonymous> (/Users/nol/code/node-red/node-red-dashboard/ui.js:293:79)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at /Users/nol/code/node-red/node-red-dashboard/node_modules/socket.io/lib/socket.js:503:12
        at nextTickCallbackWith0Args (node.js:436:9)
        at process._tickCallback (node.js:365:13)
```

I had a single `ui_tab` node with a single `ui_group` and a single `ui_text` widget. I deleted the `ui_text` widget, hit deploy and got this.

**Comment by knolleary** [comment]
This is with the latest code in master (e72b87d2332c72620a13bc828107c722fc5c9fcd).

I can no longer start Node-RED without it hitting this error.

**Comment by knolleary** [comment]
Here's the tab/group/base nodes:

```
[
    {
        "id": "f660e0d0.a407c",
        "type": "ui_tab",
        "z": "",
        "name": "Home",
        "icon": "dashboard"
    },
    {
        "id": "8ee92f6b.58767",
        "type": "ui_group",
        "z": "",
        "name": "Default",
        "tab": "f660e0d0.a407c",
        "disp": true,
        "width": "3"
    },
    {
        "id": "ca9ad696.d96b28",
        "type": "ui_base",
        "theme": {
            "name": "theme-light",
            "lightTheme": {
                "default": "#0094CE",
                "baseColor": "#0094CE",
                "baseFont": "Helvetica Neue",
                "edited": true,
                "reset": false
            },
            "darkTheme": {
                "default": "#097479",
                "baseColor": "#097479",
                "baseFont": "Helvetica Neue",
                "edited": false
            },
            "customTheme": {
                "name": "Untitled Theme 1",
                "default": "#4B7930",
                "baseColor": "#4B7930",
                "baseFont": "Helvetica Neue"
            },
            "themeState": {
                "base-color": {
                    "default": "#0094CE",
                    "value": "#0094CE",
                    "edited": false
                },
                "page-titlebar-backgroundColor": {
                    "value": "#0094CE",
                    "edited": false
                },
                "page-backgroundColor": {
                    "value": "#fafafa",
                    "edited": false
                },
                "page-sidebar-backgroundColor": {
                    "value": "#ffffff",
                    "edited": false
                },
                "group-textColor": {
                    "value": "#1bbfff",
                    "edited": false
                },
                "group-borderColor": {
                    "value": "#ffffff",
                    "edited": false
                },
                "group-backgroundColor": {
                    "value": "#ffffff",
                    "edited": false
                },
                "widget-textColor": {
                    "value": "#111111",
                    "edited": false
                },
                "widget-backgroundColor": {
                    "value": "#0094ce",
                    "edited": false
                },
                "widget-borderColor": {
                    "value": "#ffffff",
                    "edited": false
                }
            }
        },
        "site": {
            "name": "Node-RED Dashboard",
            "hideToolbar": "false",
            "allowSwipe": "false",
            "dateFormat": "DD/MM/YYYY",
            "sizes": {
                "sx": 48,
                "sy": 48,
                "gx": 6,
                "gy": 6,
                "cx": 6,
                "cy": 6,
                "px": 0,
                "py": 0
            }
        }
    }
]
```

**Comment by knolleary** [comment]
Starts fine on `2.3.10`
