### ISSUE TITLE
NR crash after deleting a Dashboard unused config node

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#341]
Using Dashboard v2.7.0 
 [red] Uncaught Exception:
16 Jan 12:17:43 - TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Socket.<anonymous> (C:\Users\username\Documents\Github\projectname\node-red\node_modules\node-red-dashboard\ui.js:349:36)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by dceejay** [comment]
fixed in master
