### ISSUE TITLE
Error while installing node-red-dashboard

### ISSUE THREAD

**Issue by mechanic98** [node-red/node-red-dashboard#397]
hi
# raspi config:
```
Node-RED version: v0.18.5
Node.js  version: v8.11.1
Linux 4.9.59-v7+ arm LE
```

## when i want to install node-red dashboard , i get this errors:
`pi@raspberrypi:~/.node-red $ sudo npm i node-red-dashboard`
```
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "node-red-dashboard"
npm ERR! node v8.11.1
npm ERR! npm  v2.15.12
npm ERR! file /home/pi/.node-red/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /home/pi/.node-red/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log

```
**and this is  npm-debug.log:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'node-red-dashboard' ]
2 info using npm@2.15.12
3 info using node@v8.11.1
4 verbose install initial load of /home/pi/.node-red/package.json
5 verbose stack Error: Failed to parse json
5 verbose stack No data, empty input at 1:1
5 verbose stack
5 verbose stack ^
5 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
5 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
6 verbose cwd /home/pi/.node-red
7 error Linux 4.9.59-v7+
8 error argv "/usr/bin/node" "/usr/bin/npm" "i" "node-red-dashboard"
9 error node v8.11.1
10 error npm  v2.15.12
11 error file /home/pi/.node-red/package.json
12 error code EJSONPARSE
13 error Failed to parse json
13 error No data, empty input at 1:1
13 error
13 error ^
14 error File: /home/pi/.node-red/package.json
15 error Failed to parse package.json data.
15 error package.json must be actual JSON, not just JavaScript.
15 error
15 error This is not a bug in npm.
15 error Tell the package author to fix their package.json file. JSON.parse
16 verbose exit [ 1, true ]

```

**Comment by dceejay** [comment]
This seems to be complaining about a file `/home/pi/.node-red/package.json` which is in your user directory. Can you share that if possible ? 
Also for some reason you seem to be using npm 2.15.12 - whereas node 8 comes with npm 5 these days.

In general we prefer how-to type questions via the slack channel or forum so the widest possible community can help out.

**Comment by mechanic98** [comment]
Tnx for reply
my package.json is completely empty!
`pi@raspberrypi:~/.node-red $ cat /home/pi/.node-red/package.json`

and now i get this error:
```
pi@raspberrypi:~/.node-red $ sudo npm i node-red-dashboard
npm ERR! file /home/pi/.node-red/package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected end of JSON input while parsing near ''
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-13T08_32_49_502Z-debug.log
```


```
root@raspberrypi:~/.npm/_logs# cat 2018-05-13T08_38_12_879Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'node-red-dashboard' ]
2 info using npm@6.0.1
3 info using node@v8.11.1
4 verbose npm-session 4a5984dbf5f49472
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing stage:rollbackFailedOptional Completed in 10ms
8 timing stage:runTopLevelLifecycles Completed in 155ms
9 verbose stack Error: Failed to parse json
9 verbose stack Unexpected end of JSON input while parsing near ''
9 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:452:11)
9 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:104:26)
9 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:5
9 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
9 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
10 verbose cwd /home/pi/.node-red
11 verbose Linux 4.9.59-v7+
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "node-red-dashboard"
13 verbose node v8.11.1
14 verbose npm  v6.0.1
15 error file /home/pi/.node-red/package.json
16 error code EJSONPARSE
17 error JSON.parse Failed to parse json
17 error JSON.parse Unexpected end of JSON input while parsing near ''
18 error JSON.parse Failed to parse package.json data.
18 error JSON.parse package.json must be actual JSON, not just JavaScript.
19 verbose exit [ 1, true ]
```

**Comment by mechanic98** [comment]
i was solved error but i now have this error:
```
root@raspberrypi:/home/pi/.node-red# npm i node-red-dashboard                   
> node-red-dashboard@2.9.3 postinstall /home/pi/.node-red/node_modules/node-red-dashboard
> node fixfa.js

npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-dashboard@2.9.3
updated 1 package in 79.049s
```

**Comment by dceejay** [comment]
those are warnings not errors so should be OK.
