### ISSUE TITLE
Text Node - Cannot have colon at end of 'label' field otherwise "Unexpected token u in JSON at position 0"

### ISSUE THREAD

**Issue by joearkay** [node-red/node-red-dashboard#521]
### What are the steps to reproduce?
Enter a colon (":") at the end of the "label" field in the text node

### What happens?

```
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at addField (/data/node_modules/node-red-dashboard/ui.js:219:61)
    at TextNode.<anonymous> (/data/node_modules/node-red-dashboard/ui.js:236:13)
    at emitOne (events.js:96:13)
    at TextNode.emit (events.js:188:7)
    at TextNode.Node.receive (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at FunctionNode.Node.send (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at sendResults (/usr/src/node-red/node_modules/node-red/nodes/core/core/80-function.js:52:18)
    at FunctionNode.<anonymous> (/usr/src/node-red/node_modules/node-red/nodes/core/core/80-function.js:225:21)
    at emitOne (events.js:96:13)
```

### What do you expect to happen?
No error

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.14.0
- [ ] Node-RED version: 0.19.5
- [ ] node.js version: Not sure
- [ ] npm version: Not sure
- [ ] Platform/OS: Ubuntu
- [ ] Browser: Chrome

**Comment by joearkay** [comment]
Perhaps unescaped JSON issue?

**Comment by joearkay** [comment]
Mixed wires - not cause of issue.
