### ISSUE TITLE
opening dashboard (/ui/) crashes node red

### ISSUE THREAD

**Issue by pinguinpfleger** [node-red/node-red-dashboard#611]
`19 Aug 22:40:43 - [red] Uncaught Exception:
19 Aug 22:40:43 - TypeError: mime.lookup is not a function
    at SendStream.type (/data/node_modules/send/index.js:838:19)
    at SendStream.send (/data/node_modules/send/index.js:627:8)
    at /data/node_modules/send/index.js:774:12
    at FSReqWrap.oncomplete (fs.js:154:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2020-08-19T20_40_43_390Z-debug.log`

cat .npm/_logs/2020-08-19T20_40_43_390Z-debug.log
`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--cache',
1 verbose cli   '/data/.npm',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.1.3~prestart: node-red-docker@1.1.3
7 info lifecycle node-red-docker@1.1.3~start: node-red-docker@1.1.3
8 verbose lifecycle node-red-docker@1.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.1.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.1.3~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.1.3~start: Args: [ '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"' ]
12 silly lifecycle node-red-docker@1.1.3~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.1.3~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid node-red-docker@1.1.3
16 verbose cwd /usr/src/node-red
17 verbose Linux 5.4.51-v7l+
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--cache" "/data/.npm" "--" "--userDir" "/data"
19 verbose node v10.22.0
20 verbose npm  v6.14.6
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.1.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`

- [ ] Node-RED-Dashboard version: 
- [ ] Node-RED version:1.1.13
- [ ] node.js version:v10.22.0
- [ ] npm version: v6.14.6
- [ ] Platform/OS: raspbian buster
- [ ] Browser: safari Version 13.1.2 (15609.3.5.1.3)

**Comment by aveseli** [comment]
I am having the same problem.

```

28 Apr 22:17:26 - [red] Uncaught Exception:
28 Apr 22:17:26 - TypeError: mime.lookup is not a function
    at SendStream.type (/data/node_modules/send/index.js:838:19)
    at SendStream.send (/data/node_modules/send/index.js:627:8)
    at /data/node_modules/send/index.js:774:12
    at FSReqWrap.oncomplete (fs.js:154:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.3.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```
