### ISSUE TITLE
[node-red-node-ui-table]: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by CreativeWarlock** [node-red/node-red-dashboard#709]
Hi there!

### Which node are you reporting an issue on?
node-red-node-ui-table

### What are the steps to reproduce?
Just import the attached flow with the example 4 from ui-table. Some nodes are disabled which may be the cause of the following null error, see below.

### What happens?
Starting Node Red with this flow leads to the following error:
`5 Jul 21:09:01 - [info] Starting flows
TypeError: Cannot read property 'id' of null
    at addControl (/data/node_modules/node-red-dashboard/ui.js:497:25)
    at Object.add (/data/node_modules/node-red-dashboard/ui.js:145:18)
    at addWidget (/data/node_modules/node-red-dashboard/index.js:119:15)
    at Object.addWidget (/data/node_modules/node-red-dashboard/index.js:137:48)
    at new TableNode (/data/node_modules/node-red-node-ui-table/node.js:89:27)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/util.js:86:27)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:205:48)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
`

Does not occur in:
- Node-Red 1.2.9 + Node.js version 10 + NPM version 6.14.10

Does occurs in:
- Node-Red 1.3.5 + Node.js version 12 & 14 + NPM version 7.19.1

Platform/OS:
Docker Container with x86_64 Linux (pulled from https://registry.hub.docker.com/r/nodered/node-red/)

Browser:
Chrome Version 91.0.4472.124 (Official Build) (64-Bit)

Zip file with the flow (stripped down to the only flow causing the error)
[Ui-Table_null_error.zip](https://github.com/node-red/node-red-ui-nodes/files/6766002/Ui-Table_null_error.zip)

Screenshot of the only flow with a ui-table node:
![image](https://user-images.githubusercontent.com/4894323/124512023-b9369000-ddd7-11eb-8b25-6dd1bd1855b6.png)

In case you need anything else, let me know.

Cheers
Marcel

**Comment by dceejay** [comment]
Hopefully fixed by https://github.com/node-red/node-red-dashboard/commit/8f9d5e2458f38e18782420c45733dfec61f03e13

**Comment by colinl** [comment]
Fixed for me in dashboard 2.30.0
