### ISSUE TITLE
ui-button crashes node-red if invalid json entered in Buffer mode

### ISSUE THREAD

**Issue by colinl** [node-red/node-red-dashboard#726]
### What are the steps to reproduce?
Configure a button to output a Buffer and enter just `[` as the payload

### What happens?
When the button is pressed node red crashes with
```
2 Sep 09:13:33 - [red] Uncaught Exception:
2 Sep 09:13:33 - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.evaluateNodeProperty (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:614:25)
    at Object.convertBack (/home/colinl/.node-red/node_modules/node-red-dashboard/nodes/ui_button.js:69:38)
    at EventEmitter.handler (/home/colinl/.node-red/node_modules/node-red-dashboard/ui.js:277:29)
    at EventEmitter.emit (events.js:412:35)
    at Socket.emit (events.js:400:28)
    at /home/colinl/.node-red/node_modules/node-red-dashboard/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
### What do you expect to happen?
Posibbly the button node should validate the JSON entered.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.30.0
- [ ] Node-RED version: 2.0.5
- [ ] node.js version: 14.17.6
- [ ] Platform/OS: Ubuntu
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
Also fixed Switch with same potential issue
